
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Aug  1 2020 20:52:38 +07 (Aug  1 2020 13:52:38 UTC)

// Verification Directory fv/bound_flasher 

module bound_flasher(clk, rst_n, flick, lamp);
  input clk, rst_n, flick;
  output [15:0] lamp;
  wire clk, rst_n, flick;
  wire [15:0] lamp;
  wire [1:0] min_max_key;
  wire [1:0] state;
  wire \lamp[14]_416 , n_3, n_5, n_6, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_17, n_18, n_19, n_20;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_40, n_41, n_42;
  wire n_43, n_44, n_46, n_49, n_50, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_66, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_100, n_101, n_102, n_103, n_104, n_105, n_106;
  wire n_107, n_108, n_109, n_110, n_111, n_112, n_113, n_114;
  wire n_115, n_116, n_117, n_118, n_119, n_120, n_121, n_122;
  wire n_123, n_124, n_125, n_126, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_152, n_153, n_154, n_155;
  wire n_156, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_193, n_196, n_205, n_210, n_211, n_214;
  wire n_217, n_222, n_223, n_226, n_227, n_230, n_237, n_241;
  wire n_242, n_252, n_257, n_262, n_264, n_265, n_267, n_268;
  wire n_269;
  DFFSRHQX8 \min_max_key_reg[1] (.RN (n_131), .SN (n_188), .CK (clk),
       .D (n_173), .Q (min_max_key[1]));
  DFFRHQX8 \lamp_reg[14] (.RN (rst_n), .CK (clk), .D (n_179), .Q
       (\lamp[14]_416 ));
  DFFSRHQX8 \min_max_key_reg[0] (.RN (n_104), .SN (n_174), .CK (clk),
       .D (n_172), .Q (min_max_key[0]));
  DFFRHQX8 \lamp_reg[8] (.RN (rst_n), .CK (clk), .D (n_187), .Q
       (lamp[8]));
  DFFRHQX8 \lamp_reg[9] (.RN (rst_n), .CK (clk), .D (n_186), .Q
       (lamp[9]));
  DFFRHQX8 \lamp_reg[10] (.RN (rst_n), .CK (clk), .D (n_185), .Q
       (lamp[10]));
  DFFRHQX8 \lamp_reg[11] (.RN (rst_n), .CK (clk), .D (n_184), .Q
       (lamp[11]));
  DFFRHQX8 \lamp_reg[13] (.RN (rst_n), .CK (clk), .D (n_182), .Q
       (lamp[13]));
  DFFRHQX8 \lamp_reg[12] (.RN (rst_n), .CK (clk), .D (n_183), .Q
       (lamp[12]));
  DFFRHQX8 \lamp_reg[1] (.RN (rst_n), .CK (clk), .D (n_180), .Q
       (lamp[1]));
  DFFRHQX8 \lamp_reg[7] (.RN (rst_n), .CK (clk), .D (n_181), .Q
       (lamp[7]));
  DFFRHQX8 \lamp_reg[6] (.RN (rst_n), .CK (clk), .D (n_177), .Q
       (lamp[6]));
  DFFRHQX8 \lamp_reg[2] (.RN (rst_n), .CK (clk), .D (n_175), .Q
       (lamp[2]));
  DFFRHQX8 \lamp_reg[5] (.RN (rst_n), .CK (clk), .D (n_176), .Q
       (lamp[5]));
  DFFRHQX8 \lamp_reg[3] (.RN (rst_n), .CK (clk), .D (n_178), .Q
       (lamp[3]));
  DFFRHQX8 \lamp_reg[4] (.RN (rst_n), .CK (clk), .D (n_189), .Q
       (lamp[4]));
  NAND2XL g5140__2398(.A (n_155), .B (n_124), .Y (n_188));
  DFFRHQX4 \lamp_reg[0] (.RN (rst_n), .CK (clk), .D (n_137), .Q
       (lamp[0]));
  OR2XL g5139__5107(.A (n_237), .B (n_154), .Y (n_174));
  AOI21X4 g5191__6260(.A0 (lamp[15]), .A1 (n_169), .B0 (n_110), .Y
       (n_171));
  AOI21X4 g5177__4319(.A0 (lamp[2]), .A1 (n_169), .B0 (n_105), .Y
       (n_170));
  AOI21X4 g5179__8428(.A0 (n_227), .A1 (n_169), .B0 (n_114), .Y
       (n_168));
  AOI21X4 g5180__5526(.A0 (n_193), .A1 (n_169), .B0 (n_118), .Y
       (n_167));
  AOI21X4 g5181__6783(.A0 (lamp[5]), .A1 (n_169), .B0 (n_116), .Y
       (n_165));
  AOI21X4 g5182__3680(.A0 (lamp[6]), .A1 (n_169), .B0 (n_119), .Y
       (n_164));
  AOI21X4 g5183__1617(.A0 (lamp[7]), .A1 (n_169), .B0 (n_113), .Y
       (n_163));
  AOI21X4 g5184__2802(.A0 (lamp[8]), .A1 (n_169), .B0 (n_112), .Y
       (n_162));
  AOI21X4 g5185__1705(.A0 (n_211), .A1 (n_169), .B0 (n_111), .Y
       (n_161));
  AOI21X4 g5186__5122(.A0 (lamp[10]), .A1 (n_169), .B0 (n_106), .Y
       (n_160));
  AOI21X4 g5187__8246(.A0 (lamp[11]), .A1 (n_169), .B0 (n_115), .Y
       (n_159));
  AOI21X4 g5188__7098(.A0 (n_223), .A1 (n_169), .B0 (n_109), .Y
       (n_158));
  AOI21X4 g5189__6131(.A0 (lamp[13]), .A1 (n_169), .B0 (n_108), .Y
       (n_157));
  AOI21X4 g5190__1881(.A0 (lamp[14]), .A1 (n_169), .B0 (n_107), .Y
       (n_156));
  INVXL g5176(.A (n_154), .Y (n_155));
  NAND2X4 g5174__5115(.A (lamp[13]), .B (n_150), .Y (n_153));
  OAI22X2 g5157__7482(.A0 (n_205), .A1 (n_135), .B0 (n_29), .B1
       (n_136), .Y (n_152));
  NAND2X4 g5161__4733(.A (lamp[1]), .B (n_150), .Y (n_151));
  NAND2X4 g5162__6161(.A (lamp[0]), .B (n_150), .Y (n_149));
  NAND2X4 g5163__9315(.A (lamp[2]), .B (n_150), .Y (n_148));
  NAND2X4 g5164__9945(.A (n_227), .B (n_150), .Y (n_147));
  NAND2X4 g5165__2883(.A (n_193), .B (n_150), .Y (n_146));
  NAND2X4 g5166__2346(.A (lamp[5]), .B (n_150), .Y (n_145));
  NAND2X4 g5167__1666(.A (lamp[6]), .B (n_150), .Y (n_144));
  NAND2X4 g5168__7410(.A (lamp[7]), .B (n_150), .Y (n_143));
  NAND2X4 g5169__6417(.A (lamp[8]), .B (n_150), .Y (n_142));
  NAND2X4 g5170__5477(.A (n_211), .B (n_150), .Y (n_141));
  NAND2X4 g5171__2398(.A (lamp[10]), .B (n_150), .Y (n_140));
  NAND2X4 g5172__5107(.A (lamp[11]), .B (n_150), .Y (n_139));
  NAND2X4 g5173__6260(.A (n_223), .B (n_150), .Y (n_138));
  OAI221X2 g5156__4319(.A0 (n_28), .A1 (n_120), .B0 (n_5), .B1 (n_136),
       .C0 (n_135), .Y (n_137));
  DFFSRHQX4 \state_reg[0] (.RN (rst_n), .SN (n_132), .CK (clk), .D
       (n_129), .Q (state[0]));
  NAND2X4 g5178__8428(.A (n_217), .B (n_133), .Y (n_134));
  NAND3BXL g5192__5526(.AN (n_132), .B (state[1]), .C (n_83), .Y
       (n_154));
  AOI31X1 g5195__6783(.A0 (n_61), .A1 (n_97), .A2 (n_121), .B0 (n_122),
       .Y (n_131));
  NAND2X4 g5160__3680(.A (n_237), .B (n_133), .Y (n_130));
  CLKINVX16 g5196(.A (n_135), .Y (n_150));
  AO21X4 g5197__1617(.A0 (state[0]), .A1 (n_128), .B0 (n_126), .Y
       (n_129));
  NAND2BX2 g5194__1705(.AN (n_124), .B (n_126), .Y (n_125));
  OR3X6 g5198__5122(.A (n_252), .B (n_257), .C (n_103), .Y (n_133));
  NOR2XL g5215__8246(.A (n_122), .B (n_121), .Y (n_123));
  NAND2XL g5209__7098(.A (n_121), .B (rst_n), .Y (n_132));
  NOR2X8 g5199__6131(.A (n_102), .B (n_126), .Y (n_135));
  CLKINVX20 g5210(.A (n_120), .Y (n_169));
  CLKAND2X2 g5204__1881(.A (lamp[5]), .B (n_117), .Y (n_119));
  CLKAND2X2 g5201__5115(.A (n_227), .B (n_117), .Y (n_118));
  CLKAND2X2 g5202__7482(.A (n_193), .B (n_117), .Y (n_116));
  CLKAND2X2 g5203__4733(.A (lamp[10]), .B (n_117), .Y (n_115));
  CLKAND2X2 g5200__6161(.A (lamp[2]), .B (n_117), .Y (n_114));
  CLKAND2X2 g5205__9315(.A (lamp[6]), .B (n_117), .Y (n_113));
  CLKAND2X2 g5206__9945(.A (lamp[7]), .B (n_117), .Y (n_112));
  CLKAND2X2 g5207__2883(.A (lamp[8]), .B (n_117), .Y (n_111));
  CLKAND2X2 g5214__2346(.A (lamp[14]), .B (n_117), .Y (n_110));
  CLKAND2X2 g5211__1666(.A (lamp[11]), .B (n_117), .Y (n_109));
  CLKAND2X2 g5212__7410(.A (n_223), .B (n_117), .Y (n_108));
  CLKAND2X2 g5213__6417(.A (lamp[13]), .B (n_117), .Y (n_107));
  CLKAND2X2 g5208__5477(.A (n_211), .B (n_117), .Y (n_106));
  CLKAND2X2 g5216__2398(.A (lamp[1]), .B (n_117), .Y (n_105));
  AOI21XL g5218__5107(.A0 (n_237), .A1 (n_103), .B0 (n_122), .Y
       (n_104));
  NOR2X8 g5220__6260(.A (n_95), .B (n_101), .Y (n_120));
  AOI21X4 g5217__4319(.A0 (n_100), .A1 (n_91), .B0 (n_56), .Y (n_102));
  CLKAND2X12 g5219__8428(.A (n_269), .B (n_98), .Y (n_126));
  INVX2 g5225(.A (n_117), .Y (n_136));
  OR2X1 g5222__5526(.A (n_26), .B (n_103), .Y (n_121));
  CLKAND2X6 g5223__6783(.A (n_93), .B (n_100), .Y (n_101));
  CLKAND2X12 g5227__3680(.A (n_96), .B (n_94), .Y (n_117));
  NOR2X8 g5226__1617(.A (n_84), .B (n_92), .Y (n_98));
  CLKAND2X6 g5229__2802(.A (flick), .B (n_97), .Y (n_103));
  NAND2X4 g5231__1705(.A (n_95), .B (n_89), .Y (n_96));
  NOR2X8 g5228__5122(.A (n_87), .B (n_86), .Y (n_100));
  AOI21X4 g5232__8246(.A0 (n_95), .A1 (n_90), .B0 (n_31), .Y (n_94));
  NOR2X6 g5237__7098(.A (n_76), .B (n_88), .Y (n_93));
  NAND2X8 g5230__6131(.A (n_78), .B (n_85), .Y (n_92));
  NOR2X4 g5238__1881(.A (n_77), .B (n_80), .Y (n_91));
  NOR2X6 g5236__5115(.A (n_90), .B (n_82), .Y (n_97));
  NAND2X8 g5246__7482(.A (n_52), .B (n_74), .Y (n_88));
  NAND2X8 g5247__4733(.A (n_36), .B (n_79), .Y (n_87));
  NOR2X6 g5239__6161(.A (n_53), .B (n_69), .Y (n_85));
  AOI22X4 g5240__9315(.A0 (n_83), .A1 (n_72), .B0 (n_262), .B1 (n_71),
       .Y (n_84));
  CLKINVX4 g5241(.A (n_81), .Y (n_82));
  NAND2X8 g5245__2883(.A (n_66), .B (n_63), .Y (n_90));
  NOR2X6 g5260__2346(.A (n_54), .B (n_35), .Y (n_79));
  NOR2X6 g5234__1666(.A (n_62), .B (n_59), .Y (n_78));
  NAND2X4 g5243__7410(.A (n_75), .B (n_73), .Y (n_77));
  CLKAND2X6 g5252__6417(.A (n_44), .B (n_73), .Y (n_74));
  OR2X6 g5244__5477(.A (n_72), .B (n_71), .Y (n_81));
  ADDHX2 g5242__2398(.A (lamp[0]), .B (n_32), .CO (n_69), .S (n_70));
  AOI21X4 g5257__5107(.A0 (n_37), .A1 (n_34), .B0 (n_33), .Y (n_68));
  NOR2X8 g5259__6260(.A (n_252), .B (n_50), .Y (n_66));
  NOR2X6 g5251__8428(.A (n_62), .B (n_43), .Y (n_63));
  INVXL g5264(.A (n_124), .Y (n_61));
  NOR2X4 g5255__5526(.A (n_55), .B (n_41), .Y (n_60));
  NOR2X4 g5268__6783(.A (lamp[0]), .B (n_58), .Y (n_59));
  CLKAND2X6 g5262__3680(.A (n_30), .B (n_38), .Y (n_75));
  NOR2X4 g5263__1617(.A (n_14), .B (n_268), .Y (n_71));
  NOR2X4 g5254__2802(.A (n_56), .B (n_55), .Y (n_57));
  NOR2X4 g5280__1705(.A (n_15), .B (n_58), .Y (n_54));
  CLKAND2X3 g5250__5122(.A (n_40), .B (n_46), .Y (n_52));
  OR2X1 g5274__8246(.A (n_262), .B (n_58), .Y (n_124));
  NAND2X6 g5266__7098(.A (lamp[0]), .B (n_49), .Y (n_50));
  CLKAND2X6 g5261__1881(.A (n_18), .B (n_27), .Y (n_72));
  INVX2 g5276(.A (n_40), .Y (n_41));
  AOI2BB1X2 g5281__7482(.A0N (lamp[5]), .A1N (n_196), .B0 (n_13), .Y
       (n_38));
  INVX2 g5289(.A (n_49), .Y (n_37));
  NAND2X2 g5269__4733(.A (lamp[11]), .B (n_83), .Y (n_36));
  NOR2X4 g5265__6161(.A (lamp[11]), .B (n_34), .Y (n_35));
  NOR2X4 g5279__9315(.A (n_9), .B (n_34), .Y (n_33));
  NAND2X6 g5283__9945(.A (n_20), .B (n_11), .Y (n_55));
  INVX1 g5300(.A (n_56), .Y (n_31));
  AOI22X2 g5282__2883(.A0 (lamp[7]), .A1 (n_242), .B0 (lamp[6]), .B1
       (min_max_key[1]), .Y (n_30));
  AOI22X4 g5286__2346(.A0 (lamp[13]), .A1 (n_29), .B0 (lamp[15]), .B1
       (n_226), .Y (n_40));
  AOI22X4 g5287__1666(.A0 (lamp[9]), .A1 (n_6), .B0 (lamp[3]), .B1
       (n_28), .Y (n_44));
  AOI22X4 g5288__7410(.A0 (lamp[10]), .A1 (n_214), .B0 (lamp[2]), .B1
       (n_230), .Y (n_46));
  CLKAND2X6 g5285__6417(.A (n_19), .B (n_12), .Y (n_42));
  NOR3X4 g5272__5477(.A (lamp[4]), .B (lamp[1]), .C (lamp[2]), .Y
       (n_27));
  NOR3BXL g5271__2398(.AN (flick), .B (state[0]), .C (state[1]), .Y
       (n_26));
  NOR2X8 g5299__5107(.A (n_241), .B (n_222), .Y (n_32));
  CLKAND2X6 g5298__6260(.A (n_210), .B (n_226), .Y (n_49));
  NAND2X4 g5310__8428(.A (n_8), .B (state[0]), .Y (n_56));
  CLKAND2X12 g5312__5526(.A (state[1]), .B (n_3), .Y (n_95));
  NOR2X6 g5292__3680(.A (lamp[13]), .B (lamp[9]), .Y (n_19));
  NOR2X2 g5296__1617(.A (lamp[5]), .B (lamp[3]), .Y (n_18));
  NOR2X4 g5294__2802(.A (lamp[11]), .B (lamp[15]), .Y (n_17));
  CLKAND2X2 g5307__5122(.A (lamp[2]), .B (lamp[4]), .Y (n_15));
  NAND2X2 g5291__8246(.A (lamp[4]), .B (lamp[3]), .Y (n_14));
  NOR2X2 g5295__7098(.A (lamp[7]), .B (min_max_key[1]), .Y (n_13));
  NOR2X6 g5306__6131(.A (lamp[8]), .B (lamp[10]), .Y (n_12));
  OR2X4 g5309__1881(.A (lamp[10]), .B (min_max_key[1]), .Y (n_11));
  NOR2X4 g5308__5115(.A (lamp[7]), .B (lamp[6]), .Y (n_10));
  CLKAND2X2 g5304__7482(.A (lamp[13]), .B (\lamp[14]_416 ), .Y (n_9));
  OR2X6 g5297__4733(.A (min_max_key[0]), .B (min_max_key[1]), .Y
       (n_34));
  OR2X6 g5311__6161(.A (min_max_key[0]), .B (min_max_key[1]), .Y
       (n_83));
  INVX2 g5315(.A (lamp[8]), .Y (n_6));
  INVX1 g5325(.A (lamp[0]), .Y (n_5));
  CLKINVX4 g5313(.A (state[0]), .Y (n_3));
  INVXL g5319(.A (rst_n), .Y (n_122));
  NAND2X6 g5350__9315(.A (n_265), .B (n_58), .Y (n_73));
  NAND2X4 g5352__9945(.A (n_125), .B (n_134), .Y (n_173));
  NAND2X4 g5354__2883(.A (n_149), .B (n_170), .Y (n_180));
  NAND2X4 g5356__2346(.A (n_267), .B (n_130), .Y (n_172));
  NAND2X4 g5358__1666(.A (n_151), .B (n_168), .Y (n_175));
  NAND2X4 g5360__7410(.A (n_148), .B (n_167), .Y (n_178));
  NAND2X4 g5362__6417(.A (n_147), .B (n_165), .Y (n_189));
  NAND2X4 g5364__5477(.A (n_142), .B (n_160), .Y (n_186));
  NAND2X4 g5366__2398(.A (n_146), .B (n_164), .Y (n_176));
  NAND2X4 g5368__5107(.A (n_153), .B (n_171), .Y (n_179));
  NAND2X4 g5370__6260(.A (n_145), .B (n_163), .Y (n_177));
  NAND2X4 g5372__4319(.A (n_141), .B (n_159), .Y (n_185));
  NAND2X8 g5374__8428(.A (n_49), .B (n_42), .Y (n_53));
  NAND2X4 g5376__5526(.A (n_139), .B (n_157), .Y (n_183));
  NAND2X4 g5378__6783(.A (n_143), .B (n_161), .Y (n_187));
  NAND2X4 g5380__3680(.A (n_140), .B (n_158), .Y (n_184));
  NAND2X4 g5382__1617(.A (n_138), .B (n_156), .Y (n_182));
  NAND2X4 g5384__2802(.A (n_144), .B (n_162), .Y (n_181));
  NAND2X6 g5386__1705(.A (n_57), .B (n_75), .Y (n_76));
  NAND2X6 g5388__5122(.A (n_68), .B (n_70), .Y (n_86));
  NAND2X6 g5392__8246(.A (flick), .B (n_81), .Y (n_89));
  OAI2BB1X4 g5396__6131(.A0N (state[1]), .A1N (n_133), .B0 (n_128), .Y
       (n_166));
  CLKINVX4 g5402(.A (n_42), .Y (n_43));
  NAND2X6 g5406__1881(.A (n_17), .B (n_10), .Y (n_62));
  BUFX16 g5408(.A (n_32), .Y (n_58));
  CLKINVX12 fopt5433(.A (min_max_key[1]), .Y (n_222));
  CLKINVX4 fopt5437(.A (lamp[12]), .Y (n_226));
  CLKINVX6 fopt5448(.A (min_max_key[0]), .Y (n_241));
  CLKINVX4 fopt5449(.A (lamp[6]), .Y (n_242));
  CLKINVX12 fopt5458(.A (n_95), .Y (n_252));
  BUFX2 fopt5467(.A (min_max_key[1]), .Y (n_217));
  DFFRX2 \state_reg[1] (.RN (n_123), .CK (clk), .D (n_166), .Q
       (state[1]), .QN (n_8));
  DFFRX4 \lamp_reg[15] (.RN (rst_n), .CK (clk), .D (n_152), .Q
       (lamp[15]), .QN (n_29));
  CLKAND2X3 g2(.A (n_44), .B (n_46), .Y (n_264));
  NAND2BX4 g5472(.AN (lamp[5]), .B (n_28), .Y (n_265));
  NAND2BX2 g5474(.AN (n_237), .B (n_126), .Y (n_267));
  NAND3X6 g5475(.A (lamp[2]), .B (lamp[5]), .C (lamp[1]), .Y (n_268));
  NOR3BX4 g5476(.AN (n_95), .B (n_217), .C (flick), .Y (n_269));
  BUFX3 fopt5478(.A (\lamp[14]_416 ), .Y (lamp[14]));
  INVX2 fopt5482(.A (lamp[4]), .Y (n_196));
  INVX3 g5484(.A (lamp[1]), .Y (n_28));
  INVX2 fopt5486(.A (lamp[9]), .Y (n_214));
  INVX1 fopt5488(.A (lamp[3]), .Y (n_230));
  NAND2X2 g5293__5490(.A (lamp[8]), .B (min_max_key[1]), .Y (n_20));
  BUFX3 fopt5492(.A (min_max_key[0]), .Y (n_237));
  BUFX3 fopt5494(.A (lamp[9]), .Y (n_211));
  BUFX3 fopt5496(.A (lamp[12]), .Y (n_223));
  BUFX3 fopt5498(.A (lamp[3]), .Y (n_227));
  BUFX3 fopt5500(.A (lamp[4]), .Y (n_193));
  INVX2 fopt5502(.A (n_98), .Y (n_257));
  INVX3 g5504(.A (n_101), .Y (n_128));
  NAND2X4 g5249__5506(.A (n_264), .B (n_60), .Y (n_80));
  INVX3 fopt5508(.A (\lamp[14]_416 ), .Y (n_210));
  INVX2 fopt5510(.A (n_83), .Y (n_262));
  INVX1 fopt5512(.A (lamp[14]), .Y (n_205));
endmodule

