
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Aug  8 2020 21:58:20 +07 (Aug  8 2020 14:58:20 UTC)

// Verification Directory fv/bound_flasher 

module bound_flasher(CLK, RST, FLICK, LED);
  input CLK, RST, FLICK;
  output [15:0] LED;
  wire CLK, RST, FLICK;
  wire [15:0] LED;
  wire [1:0] state;
  wire [1:0] min_max_key;
  wire \LED[4]_381 , \LED[7]_384 , \LED[14]_391 , \LED[15]_392 , n_0,
       n_2, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_19, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_28, n_29, n_34, n_35, n_38, n_39;
  wire n_42, n_45, n_48, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_60, n_64, n_67, n_73;
  wire n_74, n_75, n_76, n_78, n_79, n_82, n_83, n_84;
  wire n_86, n_87, n_88, n_90, n_91, n_92, n_93, n_94;
  wire n_96, n_97, n_101, n_102, n_103, n_104, n_105, n_106;
  wire n_107, n_109, n_110, n_111, n_112, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_144;
  wire n_149, n_150, n_152, n_154, n_160, n_161, n_165, n_170;
  wire n_171, n_173, n_176, n_181, n_183, n_184, n_188, n_189;
  wire n_195, n_198, n_202, n_204, n_205, n_207, n_216, n_217;
  wire n_248, n_249, n_250, n_254, n_255, n_256, n_257, n_259;
  wire n_261, n_262, n_263, n_264, n_265, n_276, n_277, n_278;
  wire n_279, n_280, n_281, n_282, n_283, n_284, n_335, n_336;
  wire n_377;
  DFFRHQX4 \LED_reg[11] (.RN (RST), .CK (CLK), .D (n_132), .Q
       (LED[11]));
  DFFRHQX4 \LED_reg[9] (.RN (RST), .CK (CLK), .D (n_131), .Q (LED[9]));
  DFFRHQX4 \LED_reg[10] (.RN (RST), .CK (CLK), .D (n_129), .Q
       (LED[10]));
  DFFRHQX8 \LED_reg[5] (.RN (RST), .CK (CLK), .D (n_126), .Q (LED[5]));
  DFFRHQX4 \LED_reg[7] (.RN (RST), .CK (CLK), .D (n_124), .Q
       (\LED[7]_384 ));
  DFFRHQX8 \LED_reg[6] (.RN (RST), .CK (CLK), .D (n_125), .Q (LED[6]));
  DFFRHQX8 \LED_reg[8] (.RN (RST), .CK (CLK), .D (n_128), .Q (LED[8]));
  DFFRHQX4 \LED_reg[1] (.RN (RST), .CK (CLK), .D (n_133), .Q (LED[1]));
  DFFRHQX8 \LED_reg[12] (.RN (RST), .CK (CLK), .D (n_135), .Q
       (LED[12]));
  DFFRHQX8 \LED_reg[3] (.RN (RST), .CK (CLK), .D (n_127), .Q (LED[3]));
  DFFRHQX8 \LED_reg[0] (.RN (RST), .CK (CLK), .D (n_130), .Q (LED[0]));
  DFFRHQX4 \LED_reg[14] (.RN (RST), .CK (CLK), .D (n_138), .Q
       (\LED[14]_391 ));
  DFFRHQX8 \LED_reg[2] (.RN (RST), .CK (CLK), .D (n_139), .Q (LED[2]));
  DFFRHQX4 \LED_reg[4] (.RN (RST), .CK (CLK), .D (n_136), .Q
       (\LED[4]_381 ));
  DFFRHQX8 \LED_reg[13] (.RN (RST), .CK (CLK), .D (n_134), .Q
       (LED[13]));
  OAI21X4 g4098__2398(.A0 (n_183), .A1 (n_137), .B0 (n_115), .Y
       (n_139));
  OAI21X4 g4093__5107(.A0 (n_189), .A1 (n_137), .B0 (n_122), .Y
       (n_138));
  OAI21X4 g4094__6260(.A0 (n_154), .A1 (n_137), .B0 (n_109), .Y
       (n_136));
  OAI21X4 g4095__4319(.A0 (n_170), .A1 (n_137), .B0 (n_116), .Y
       (n_135));
  OAI21X4 g4096__8428(.A0 (n_176), .A1 (n_137), .B0 (n_121), .Y
       (n_134));
  OAI21X4 g4097__5526(.A0 (n_149), .A1 (n_137), .B0 (n_118), .Y
       (n_133));
  OAI21X4 g4092__6783(.A0 (n_26), .A1 (n_137), .B0 (n_117), .Y (n_132));
  OAI21X4 g4084__3680(.A0 (n_204), .A1 (n_137), .B0 (n_111), .Y
       (n_131));
  OAI21X4 g4100__1617(.A0 (n_144), .A1 (n_137), .B0 (n_110), .Y
       (n_130));
  OAI21X4 g4083__2802(.A0 (n_160), .A1 (n_137), .B0 (n_114), .Y
       (n_129));
  OAI21X4 g4085__1705(.A0 (n_5), .A1 (n_137), .B0 (n_104), .Y (n_128));
  OAI21X4 g4099__5122(.A0 (n_24), .A1 (n_137), .B0 (n_112), .Y (n_127));
  OAI21X4 g4086__8246(.A0 (n_56), .A1 (n_137), .B0 (n_107), .Y (n_126));
  OAI21X4 g4087__7098(.A0 (n_4), .A1 (n_137), .B0 (n_106), .Y (n_125));
  OAI21X4 g4088__6131(.A0 (n_198), .A1 (n_137), .B0 (n_105), .Y
       (n_124));
  DFFRHQX4 \state_reg[1] (.RN (n_91), .CK (CLK), .D (n_282), .Q
       (state[1]));
  OAI21X4 g4101__1881(.A0 (n_165), .A1 (n_137), .B0 (n_101), .Y
       (n_123));
  DFFRHQX8 \min_max_key_reg[1] (.RN (RST), .CK (CLK), .D (n_103), .Q
       (min_max_key[1]));
  AOI22X4 g4115__5115(.A0 (LED[13]), .A1 (n_120), .B0 (LED[15]), .B1
       (n_119), .Y (n_122));
  AOI22X4 g4114__7482(.A0 (n_171), .A1 (n_120), .B0 (LED[14]), .B1
       (n_119), .Y (n_121));
  AOI22X4 g4117__4733(.A0 (LED[0]), .A1 (n_120), .B0 (n_184), .B1
       (n_119), .Y (n_118));
  AOI22X4 g4112__6161(.A0 (n_161), .A1 (n_120), .B0 (n_171), .B1
       (n_119), .Y (n_117));
  AOI22X4 g4113__9315(.A0 (n_11), .A1 (n_120), .B0 (LED[13]), .B1
       (n_119), .Y (n_116));
  AOI22X4 g4118__9945(.A0 (n_150), .A1 (n_120), .B0 (n_12), .B1
       (n_119), .Y (n_115));
  AOI22X4 g4119__2883(.A0 (n_205), .A1 (n_120), .B0 (n_11), .B1
       (n_119), .Y (n_114));
  SDFFRHQX4 \min_max_key_reg[0] (.RN (RST), .CK (CLK), .D (n_97), .SI
       (n_102), .SE (min_max_key[0]), .Q (min_max_key[0]));
  AOI22X4 g4111__2346(.A0 (n_184), .A1 (n_120), .B0 (LED[4]), .B1
       (n_119), .Y (n_112));
  AOI22X4 g4102__1666(.A0 (LED[8]), .A1 (n_120), .B0 (n_161), .B1
       (n_119), .Y (n_111));
  AOI21X4 g4104__7410(.A0 (n_150), .A1 (n_119), .B0 (n_120), .Y
       (n_110));
  AOI22X4 g4105__6417(.A0 (n_12), .A1 (n_120), .B0 (LED[5]), .B1
       (n_119), .Y (n_109));
  AOI22X4 g4106__5477(.A0 (LED[4]), .A1 (n_120), .B0 (LED[6]), .B1
       (n_119), .Y (n_107));
  AOI22X4 g4107__2398(.A0 (LED[5]), .A1 (n_120), .B0 (LED[7]), .B1
       (n_119), .Y (n_106));
  AOI22X4 g4108__5107(.A0 (LED[6]), .A1 (n_120), .B0 (LED[8]), .B1
       (n_119), .Y (n_105));
  AOI22X4 g4109__6260(.A0 (LED[7]), .A1 (n_120), .B0 (n_205), .B1
       (n_119), .Y (n_104));
  DFFSRHQX2 \state_reg[0] (.RN (RST), .SN (n_93), .CK (CLK), .D
       (n_283), .Q (state[0]));
  NAND2X4 g4120__4319(.A (LED[14]), .B (n_120), .Y (n_101));
  CLKINVX20 g4121(.A (n_96), .Y (n_137));
  NOR2X8 g4123__5526(.A (n_86), .B (n_90), .Y (n_96));
  CLKINVX20 g4127(.A (n_284), .Y (n_119));
  CLKINVX20 g4128(.A (n_94), .Y (n_120));
  OR3X4 g4130__6783(.A (n_377), .B (n_84), .C (n_92), .Y (n_102));
  NOR2X8 g4132__1617(.A (n_87), .B (n_97), .Y (n_94));
  NAND2XL g4125__2802(.A (n_92), .B (RST), .Y (n_93));
  NOR2XL g4126__1705(.A (n_2), .B (n_92), .Y (n_91));
  NOR2X8 g4129__5122(.A (n_75), .B (n_92), .Y (n_90));
  NAND2X1 g4124__8246(.A (min_max_key[0]), .B (n_97), .Y (n_88));
  NOR2X6 g4134__7098(.A (n_29), .B (n_261), .Y (n_87));
  CLKAND2X12 g4137__1881(.A (n_82), .B (n_83), .Y (n_92));
  NOR2X8 g4136__5115(.A (n_79), .B (n_84), .Y (n_97));
  NOR2X6 g4138__4733(.A (n_335), .B (n_78), .Y (n_83));
  NAND2X8 g4140__6161(.A (n_336), .B (n_76), .Y (n_84));
  NAND2X4 g4141__9315(.A (state[1]), .B (n_74), .Y (n_82));
  NAND2X6 g4143__2883(.A (n_73), .B (n_78), .Y (n_79));
  AOI21X4 g4145__1666(.A0 (n_50), .A1 (n_64), .B0 (n_75), .Y (n_76));
  INVX3 g4150(.A (n_73), .Y (n_74));
  CLKAND2X6 g4154__6260(.A (n_67), .B (n_60), .Y (n_73));
  NOR2X4 g4157__8428(.A (n_195), .B (n_48), .Y (n_60));
  AOI21X4 g4158__5526(.A0 (n_17), .A1 (n_12), .B0 (n_56), .Y (n_57));
  NAND2X6 g4166__6783(.A (n_21), .B (n_217), .Y (n_64));
  NOR2X6 g4159__3680(.A (n_35), .B (n_39), .Y (n_67));
  OAI21X4 g4162__1617(.A0 (n_11), .A1 (n_45), .B0 (n_19), .Y (n_55));
  OAI22X4 g4165__2802(.A0 (LED[5]), .A1 (n_53), .B0 (LED[4]), .B1
       (n_16), .Y (n_54));
  CLKAND2X3 g4167__1705(.A (n_53), .B (n_22), .Y (n_58));
  NOR2X6 g4173__5122(.A (n_25), .B (n_8), .Y (n_52));
  NOR2X4 g4172__8246(.A (n_7), .B (n_50), .Y (n_51));
  AOI22X4 g4170__1881(.A0 (\LED[15]_392 ), .A1 (n_188), .B0 (LED[8]),
       .B1 (n_207), .Y (n_42));
  NAND2X6 g4177__5115(.A (n_6), .B (n_13), .Y (n_39));
  AOI22X4 g4175__7482(.A0 (\LED[14]_391 ), .A1 (n_173), .B0 (LED[3]),
       .B1 (n_181), .Y (n_38));
  AOI22X4 g4179__6161(.A0 (LED[0]), .A1 (n_152), .B0 (LED[2]), .B1
       (n_144), .Y (n_34));
  INVX1 g4190(.A (n_86), .Y (n_29));
  NOR2X4 g4185__9945(.A (LED[8]), .B (n_262), .Y (n_25));
  CLKAND2X2 g4200__2883(.A (state[0]), .B (n_23), .Y (n_86));
  NOR3X4 g4171__1666(.A (LED[2]), .B (LED[3]), .C (LED[0]), .Y (n_22));
  NOR2X4 g4195__7410(.A (n_154), .B (n_152), .Y (n_21));
  NAND2X2 g4196__6417(.A (LED[13]), .B (n_165), .Y (n_19));
  INVX3 g4181(.A (n_16), .Y (n_17));
  NAND2X8 g4189__5477(.A (n_0), .B (FLICK), .Y (n_78));
  CLKINVX8 g4193(.A (n_45), .Y (n_50));
  NOR2X6 g4186__2398(.A (\LED[7]_384 ), .B (LED[6]), .Y (n_15));
  NOR2X4 g4198__5107(.A (LED[11]), .B (LED[5]), .Y (n_14));
  NOR2X6 g4197__6260(.A (LED[10]), .B (LED[8]), .Y (n_13));
  CLKAND2X6 g4188__4319(.A (min_max_key[0]), .B (min_max_key[1]), .Y
       (n_16));
  NOR2X4 g4187__5526(.A (\LED[15]_392 ), .B (\LED[14]_391 ), .Y (n_9));
  NOR2X2 g4194__6783(.A (min_max_key[1]), .B (LED[6]), .Y (n_8));
  NOR2X2 g4183__3680(.A (LED[13]), .B (LED[11]), .Y (n_7));
  NOR2X6 g4184__1617(.A (LED[12]), .B (LED[13]), .Y (n_6));
  NOR2X4 g4199__2802(.A (LED[1]), .B (\LED[4]_381 ), .Y (n_53));
  OR2X6 g4202__1705(.A (min_max_key[0]), .B (min_max_key[1]), .Y
       (n_45));
  INVXL g4212(.A (RST), .Y (n_2));
  INVX2 g4220(.A (LED[5]), .Y (n_56));
  INVX2 g4203(.A (state[1]), .Y (n_23));
  INVX1 g4213(.A (state[0]), .Y (n_0));
  BUFX3 g4226(.A (LED[3]), .Y (n_12));
  INVX6 fopt4257(.A (LED[0]), .Y (n_144));
  INVX6 fopt4261(.A (LED[1]), .Y (n_152));
  CLKINVX4 fopt4265(.A (n_154), .Y (LED[4]));
  CLKINVX4 fopt4266(.A (\LED[4]_381 ), .Y (n_154));
  CLKINVX8 fopt4278(.A (LED[12]), .Y (n_173));
  INVX6 fopt4284(.A (LED[2]), .Y (n_181));
  CLKINVX4 fopt4289(.A (\LED[14]_391 ), .Y (n_188));
  OAI2BB1X4 g4304__5115(.A0N (n_195), .A1N (n_102), .B0 (n_88), .Y
       (n_103));
  NAND2X6 g4306__7482(.A (n_9), .B (n_15), .Y (n_35));
  NAND2X6 g4308__4733(.A (n_207), .B (n_14), .Y (n_48));
  CLKINVX4 fopt4314(.A (LED[9]), .Y (n_207));
  NOR2X6 g4169__4329(.A (n_181), .B (n_216), .Y (n_217));
  NAND2X6 g4182__4354(.A (LED[3]), .B (LED[0]), .Y (n_216));
  NAND2X8 g103(.A (n_250), .B (n_278), .Y (n_254));
  NOR2X6 g104(.A (n_248), .B (n_249), .Y (n_250));
  AOI21X4 g105(.A0 (n_173), .A1 (n_45), .B0 (LED[13]), .Y (n_248));
  NAND2X6 g108(.A (n_38), .B (n_34), .Y (n_249));
  NAND2X8 g107(.A (n_255), .B (n_256), .Y (n_257));
  NOR2X6 g110(.A (n_51), .B (n_55), .Y (n_255));
  NOR2X6 g111(.A (n_54), .B (n_57), .Y (n_256));
  INVX1 g14(.A (n_86), .Y (n_259));
  NOR2X6 g13(.A (n_254), .B (n_257), .Y (n_261));
  OAI22X4 g54(.A0 (min_max_key[1]), .A1 (n_262), .B0 (LED[9]), .B1
       (n_263), .Y (n_264));
  CLKINVX6 g56(.A (LED[10]), .Y (n_262));
  CLKINVX6 g55(.A (min_max_key[1]), .Y (n_263));
  AOI22X4 g53(.A0 (min_max_key[1]), .A1 (\LED[7]_384 ), .B0 (LED[6]),
       .B1 (n_202), .Y (n_265));
  NOR2X8 g23(.A (n_276), .B (n_277), .Y (n_278));
  NAND2X8 g24(.A (n_42), .B (n_52), .Y (n_276));
  NAND2X6 g25(.A (n_264), .B (n_265), .Y (n_277));
  NAND2X2 g50(.A (n_280), .B (n_281), .Y (n_282));
  INVX2 g51(.A (n_279), .Y (n_280));
  NOR3X8 g52(.A (n_259), .B (n_254), .C (n_257), .Y (n_279));
  NAND2X2 g4384(.A (state[1]), .B (n_102), .Y (n_281));
  AO21X1 g48(.A0 (state[0]), .A1 (n_280), .B0 (n_97), .Y (n_283));
  NOR2X8 g49(.A (n_28), .B (n_279), .Y (n_284));
  DFFRX4 \LED_reg[15] (.RN (RST), .CK (CLK), .D (n_123), .Q
       (\LED[15]_392 ), .QN (n_165));
  NOR3BX4 g2(.AN (n_64), .B (n_23), .C (n_58), .Y (n_335));
  INVX2 fopt4437(.A (n_165), .Y (LED[15]));
  BUFX3 fopt4439(.A (\LED[14]_391 ), .Y (LED[14]));
  BUFX4 fopt4441(.A (\LED[7]_384 ), .Y (LED[7]));
  BUFX6 g4443(.A (LED[11]), .Y (n_11));
  BUFX4 fopt4445(.A (LED[10]), .Y (n_161));
  INVX2 fopt4447(.A (\LED[7]_384 ), .Y (n_202));
  BUFX4 fopt4449(.A (LED[12]), .Y (n_171));
  BUFX4 fopt4451(.A (LED[9]), .Y (n_205));
  INVX1 g4453(.A (LED[6]), .Y (n_4));
  INVX1 g4455(.A (LED[8]), .Y (n_5));
  BUFX4 fopt4457(.A (LED[1]), .Y (n_150));
  BUFX4 fopt4459(.A (LED[2]), .Y (n_184));
  INVX1 fopt4461(.A (LED[13]), .Y (n_176));
  INVX1 g4463(.A (n_11), .Y (n_26));
  OR2X6 g4201__4465(.A (state[0]), .B (n_23), .Y (n_75));
  INVX2 fopt4467(.A (n_263), .Y (n_195));
  INVX1 fopt4469(.A (n_205), .Y (n_204));
  INVX1 fopt4471(.A (n_161), .Y (n_160));
  INVX1 fopt4473(.A (LED[7]), .Y (n_198));
  INVX1 fopt4475(.A (n_150), .Y (n_149));
  INVX1 fopt4477(.A (n_171), .Y (n_170));
  INVX1 g4479(.A (n_12), .Y (n_24));
  INVX2 fopt4481(.A (LED[14]), .Y (n_189));
  INVX1 fopt4483(.A (n_184), .Y (n_183));
  OR2X4 g4485(.A (n_50), .B (n_58), .Y (n_336));
  INVX2 g4487(.A (n_75), .Y (n_28));
  NAND2BX1 g4528(.AN (n_48), .B (n_67), .Y (n_377));
endmodule

