
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Aug  7 2020 12:33:09 +07 (Aug  7 2020 05:33:09 UTC)

// Verification Directory fv/bound_flasher 

module bound_flasher(CLK, RST, FLICK, LED);
  input CLK, RST, FLICK;
  output [15:0] LED;
  wire CLK, RST, FLICK;
  wire [15:0] LED;
  wire [1:0] min_max_key;
  wire [1:0] state;
  wire \LED[0]_401 , \LED[1]_402 , \LED[6]_407 , \LED[7]_408 ,
       \LED[10]_411 , \LED[13]_414 , \LED[14]_415 , n_6;
  wire n_7, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_18, n_19, n_22, n_24, n_25, n_26, n_27;
  wire n_28, n_30, n_32, n_33, n_34, n_37, n_38, n_40;
  wire n_41, n_43, n_44, n_45, n_46, n_48, n_49, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_84, n_85;
  wire n_86, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_133, n_135, n_136, n_137;
  wire n_138, n_140, n_141, n_142, n_143, n_144, n_145, n_146;
  wire n_147, n_148, n_149, n_150, n_151, n_152, n_153, n_154;
  wire n_158, n_165, n_168, n_176, n_183, n_185, n_190, n_199;
  wire n_201, n_212, n_214, n_215, n_219, n_220, n_222, n_230;
  wire n_241, n_245, n_274, n_280, n_281;
  DFFSRHQX8 \min_max_key_reg[0] (.RN (n_92), .SN (n_143), .CK (CLK), .D
       (n_88), .Q (min_max_key[0]));
  DFFSRHQX8 \min_max_key_reg[1] (.RN (n_95), .SN (n_142), .CK (CLK), .D
       (n_90), .Q (min_max_key[1]));
  DFFRHQX8 \LED_reg[12] (.RN (RST), .CK (CLK), .D (n_146), .Q
       (LED[12]));
  DFFRHQX8 \LED_reg[6] (.RN (RST), .CK (CLK), .D (n_154), .Q
       (\LED[6]_407 ));
  DFFRHQX8 \LED_reg[7] (.RN (RST), .CK (CLK), .D (n_151), .Q
       (\LED[7]_408 ));
  DFFRHQX8 \LED_reg[8] (.RN (RST), .CK (CLK), .D (n_152), .Q (LED[8]));
  DFFRHQX8 \LED_reg[14] (.RN (RST), .CK (CLK), .D (n_144), .Q
       (\LED[14]_415 ));
  DFFRHQX8 \LED_reg[10] (.RN (RST), .CK (CLK), .D (n_153), .Q
       (\LED[10]_411 ));
  DFFRHQX8 \LED_reg[11] (.RN (RST), .CK (CLK), .D (n_147), .Q
       (LED[11]));
  DFFRHQX8 \LED_reg[1] (.RN (RST), .CK (CLK), .D (n_148), .Q
       (\LED[1]_402 ));
  DFFRHQX8 \LED_reg[0] (.RN (RST), .CK (CLK), .D (n_149), .Q
       (\LED[0]_401 ));
  DFFRHQX8 \LED_reg[9] (.RN (RST), .CK (CLK), .D (n_150), .Q (LED[9]));
  DFFRHQX8 \LED_reg[13] (.RN (RST), .CK (CLK), .D (n_145), .Q
       (\LED[13]_414 ));
  NAND2X2 g5390__2398(.A (n_110), .B (n_133), .Y (n_154));
  NAND2X2 g5386__5107(.A (n_115), .B (n_122), .Y (n_153));
  NAND2X2 g5388__6260(.A (n_117), .B (n_140), .Y (n_152));
  NAND2X2 g5391__4319(.A (n_114), .B (n_131), .Y (n_151));
  NAND2X2 g5387__8428(.A (n_116), .B (n_121), .Y (n_150));
  DFFRHQX8 \LED_reg[15] (.RN (RST), .CK (CLK), .D (n_280), .Q
       (LED[15]));
  DFFRHQX8 \LED_reg[4] (.RN (RST), .CK (CLK), .D (n_138), .Q (LED[4]));
  DFFRHQX8 \LED_reg[3] (.RN (RST), .CK (CLK), .D (n_135), .Q (LED[3]));
  DFFRHQX8 \LED_reg[5] (.RN (RST), .CK (CLK), .D (n_130), .Q (LED[5]));
  OAI2BB1X2 g5403__5526(.A0N (LED[0]), .A1N (n_274), .B0 (n_129), .Y
       (n_149));
  NAND2X2 g5399__6783(.A (n_107), .B (n_124), .Y (n_148));
  DFFRHQX4 \state_reg[1] (.RN (n_99), .CK (CLK), .D (n_281), .Q
       (state[1]));
  NAND2X2 g5395__3680(.A (n_120), .B (n_128), .Y (n_147));
  NAND2X2 g5396__1617(.A (n_113), .B (n_127), .Y (n_146));
  NAND2X2 g5397__2802(.A (n_112), .B (n_126), .Y (n_145));
  NAND2X2 g5398__1705(.A (n_111), .B (n_125), .Y (n_144));
  DFFSRHQX4 \state_reg[0] (.RN (RST), .SN (n_103), .CK (CLK), .D
       (n_123), .Q (state[0]));
  DFFRHQX8 \LED_reg[2] (.RN (RST), .CK (CLK), .D (n_137), .Q (LED[2]));
  OR2XL g5378__5122(.A (min_max_key[0]), .B (n_141), .Y (n_143));
  NAND2BXL g5377__8246(.AN (n_141), .B (min_max_key[0]), .Y (n_142));
  NAND2X4 g5407__7098(.A (LED[7]), .B (n_165), .Y (n_140));
  OAI21X2 g5400__6131(.A0 (n_190), .A1 (n_168), .B0 (n_106), .Y
       (n_138));
  OAI21X2 g5401__1881(.A0 (n_158), .A1 (n_168), .B0 (n_104), .Y
       (n_137));
  OAI21X2 g5402__5115(.A0 (n_201), .A1 (n_168), .B0 (n_105), .Y
       (n_135));
  NAND2X4 g5405__4733(.A (LED[5]), .B (n_165), .Y (n_133));
  NAND2X4 g5406__6161(.A (LED[6]), .B (n_165), .Y (n_131));
  OAI21X2 g5389__9315(.A0 (n_230), .A1 (n_168), .B0 (n_109), .Y
       (n_130));
  NAND2X4 g5410__9945(.A (LED[10]), .B (n_165), .Y (n_128));
  NAND2X4 g5411__2883(.A (LED[11]), .B (n_165), .Y (n_127));
  NAND2X4 g5412__2346(.A (LED[12]), .B (n_165), .Y (n_126));
  NAND2X4 g5413__1666(.A (LED[13]), .B (n_165), .Y (n_125));
  NAND2X4 g5414__7410(.A (LED[0]), .B (n_165), .Y (n_124));
  NAND2X4 g5409__6417(.A (LED[9]), .B (n_165), .Y (n_122));
  NAND2X4 g5408__5477(.A (LED[8]), .B (n_165), .Y (n_121));
  NAND3XL g5392__2398(.A (n_220), .B (n_41), .C (n_102), .Y (n_141));
  AOI22X2 g5424__5107(.A0 (LED[12]), .A1 (n_119), .B0 (LED[11]), .B1
       (n_274), .Y (n_120));
  AOI22X2 g5421__6260(.A0 (LED[9]), .A1 (n_119), .B0 (LED[8]), .B1
       (n_274), .Y (n_117));
  AOI22X2 g5422__4319(.A0 (LED[10]), .A1 (n_119), .B0 (LED[9]), .B1
       (n_274), .Y (n_116));
  AOI22X2 g5423__8428(.A0 (LED[11]), .A1 (n_119), .B0 (LED[10]), .B1
       (n_274), .Y (n_115));
  AOI22X2 g5420__5526(.A0 (LED[8]), .A1 (n_119), .B0 (LED[7]), .B1
       (n_274), .Y (n_114));
  AOI22X2 g5425__6783(.A0 (LED[13]), .A1 (n_119), .B0 (LED[12]), .B1
       (n_274), .Y (n_113));
  AOI22X2 g5426__3680(.A0 (LED[14]), .A1 (n_119), .B0 (LED[13]), .B1
       (n_274), .Y (n_112));
  AOI22X2 g5427__1617(.A0 (LED[15]), .A1 (n_119), .B0 (LED[14]), .B1
       (n_274), .Y (n_111));
  AOI22X2 g5419__2802(.A0 (LED[7]), .A1 (n_119), .B0 (LED[6]), .B1
       (n_274), .Y (n_110));
  AOI21X2 g5431__1705(.A0 (LED[6]), .A1 (n_119), .B0 (n_97), .Y
       (n_109));
  AOI22X2 g5428__8246(.A0 (LED[2]), .A1 (n_119), .B0 (LED[1]), .B1
       (n_274), .Y (n_107));
  AOI21X2 g5417__7098(.A0 (LED[5]), .A1 (n_119), .B0 (n_98), .Y
       (n_106));
  AOI21X2 g5418__6131(.A0 (LED[4]), .A1 (n_119), .B0 (n_94), .Y
       (n_105));
  AOI21X2 g5430__1881(.A0 (LED[3]), .A1 (n_119), .B0 (n_96), .Y
       (n_104));
  INVXL g5432(.A (n_102), .Y (n_103));
  NOR2X8 g5445__5115(.A (n_86), .B (n_84), .Y (n_136));
  AND2XL g5435__7482(.A (RST), .B (n_93), .Y (n_99));
  CLKAND2X2 g5433__4733(.A (LED[4]), .B (n_118), .Y (n_98));
  CLKAND2X2 g5434__6161(.A (LED[5]), .B (n_118), .Y (n_97));
  CLKAND2X2 g5436__9315(.A (LED[2]), .B (n_118), .Y (n_96));
  OA21X1 g5441__9945(.A0 (n_52), .A1 (n_80), .B0 (RST), .Y (n_95));
  CLKAND2X2 g5440__2883(.A (LED[3]), .B (n_118), .Y (n_94));
  NOR2X6 g5450__2346(.A (n_41), .B (n_82), .Y (n_100));
  NOR2XL g5438__1666(.A (n_91), .B (n_93), .Y (n_102));
  AOI21XL g5442__7410(.A0 (min_max_key[0]), .A1 (n_83), .B0 (n_91), .Y
       (n_92));
  MX2X1 g5443__6417(.A (n_51), .B (n_220), .S0 (n_89), .Y (n_90));
  MX2X1 g5444__5477(.A (n_214), .B (min_max_key[0]), .S0 (n_89), .Y
       (n_88));
  NOR2X6 g5448__2398(.A (n_58), .B (n_81), .Y (n_86));
  INVX1 g5446(.A (n_84), .Y (n_85));
  NAND2X8 g5453__5107(.A (n_75), .B (n_79), .Y (n_119));
  NOR2X8 g5449__6260(.A (n_220), .B (n_89), .Y (n_84));
  AOI31X1 g5452__4319(.A0 (n_13), .A1 (n_49), .A2 (FLICK), .B0 (n_83),
       .Y (n_93));
  CLKAND2X12 g5454__8428(.A (n_73), .B (n_76), .Y (n_118));
  INVXL g5456(.A (n_83), .Y (n_80));
  CLKAND2X6 g5458__5526(.A (n_78), .B (n_77), .Y (n_81));
  NAND2BX4 g5457__6783(.AN (n_75), .B (n_74), .Y (n_76));
  NOR2XL g5459__3680(.A (n_72), .B (n_74), .Y (n_83));
  NAND2X8 g5462__1617(.A (n_70), .B (n_71), .Y (n_89));
  AOI21X4 g5461__2802(.A0 (n_45), .A1 (n_72), .B0 (n_57), .Y (n_73));
  NOR2X6 g5466__1705(.A (n_54), .B (n_68), .Y (n_78));
  NOR2X6 g5463__5122(.A (FLICK), .B (n_72), .Y (n_71));
  NAND2X8 g5464__8246(.A (n_67), .B (FLICK), .Y (n_74));
  NOR2X8 g5467__7098(.A (n_62), .B (n_64), .Y (n_77));
  OAI22X4 g5465__6131(.A0 (n_214), .A1 (n_66), .B0 (n_215), .B1 (n_65),
       .Y (n_70));
  NAND2X8 g5470__1881(.A (n_53), .B (n_61), .Y (n_64));
  NAND2X8 g5471__5115(.A (n_46), .B (n_56), .Y (n_72));
  CLKAND2X6 g5479__7482(.A (n_27), .B (n_48), .Y (n_63));
  OAI21X4 g5482__4733(.A0 (LED[5]), .A1 (n_43), .B0 (n_44), .Y (n_62));
  NOR2X6 g5473__6161(.A (n_37), .B (n_34), .Y (n_61));
  INVX1 g5498(.A (n_57), .Y (n_58));
  NOR2X6 g5474__9315(.A (n_24), .B (n_38), .Y (n_56));
  NOR2X6 g5480__9945(.A (n_30), .B (n_32), .Y (n_55));
  OAI21X2 g5481__2883(.A0 (n_199), .A1 (n_69), .B0 (n_26), .Y (n_54));
  CLKAND2X6 g5475__2346(.A (n_40), .B (n_33), .Y (n_53));
  NAND2X8 g5477__1666(.A (n_9), .B (n_28), .Y (n_65));
  ADDHX1 g5472__7410(.A (min_max_key[0]), .B (n_222), .CO (n_51), .S
       (n_52));
  NOR2X2 g5504__6417(.A (state[1]), .B (n_49), .Y (n_57));
  AOI21X4 g5483__5477(.A0 (n_245), .A1 (n_219), .B0 (n_22), .Y (n_48));
  CLKAND2X6 g5478__2398(.A (n_18), .B (n_45), .Y (n_46));
  INVX2 g5527(.A (n_13), .Y (n_41));
  AOI22X4 g5494__5107(.A0 (\LED[7]_408 ), .A1 (n_212), .B0 (LED[5]),
       .B1 (n_230), .Y (n_40));
  OAI22X4 g5496__6260(.A0 (LED[2]), .A1 (n_158), .B0 (\LED[1]_402 ),
       .B1 (n_190), .Y (n_37));
  OAI22X4 g5497__4319(.A0 (LED[3]), .A1 (n_176), .B0 (\LED[0]_401 ),
       .B1 (n_230), .Y (n_34));
  AOI22X4 g5493__8428(.A0 (n_183), .A1 (n_219), .B0 (LED[6]), .B1
       (min_max_key[1]), .Y (n_33));
  INVX2 g5506(.A (n_45), .Y (n_75));
  OAI22X4 g5492__5526(.A0 (\LED[13]_414 ), .A1 (n_25), .B0 (LED[8]),
       .B1 (n_245), .Y (n_32));
  OAI22X4 g5491__6783(.A0 (LED[12]), .A1 (n_185), .B0 (LED[9]), .B1
       (n_7), .Y (n_30));
  NOR2X6 g5487__3680(.A (n_158), .B (n_14), .Y (n_28));
  AOI22X4 g5488__1617(.A0 (LED[15]), .A1 (n_185), .B0 (LED[9]), .B1
       (min_max_key[1]), .Y (n_27));
  NAND2X4 g5489__2802(.A (n_25), .B (n_69), .Y (n_26));
  NAND2X8 g5490__1705(.A (n_11), .B (n_12), .Y (n_24));
  NOR2X4 g5509__5122(.A (LED[15]), .B (n_241), .Y (n_22));
  NOR2X4 g5511__8246(.A (n_6), .B (n_219), .Y (n_43));
  NOR3X6 g5485__7098(.A (LED[3]), .B (\LED[0]_401 ), .C (LED[4]), .Y
       (n_19));
  NOR3X6 g5486__6131(.A (LED[15]), .B (LED[8]), .C (LED[9]), .Y (n_18));
  NOR2X6 g5512__1881(.A (n_13), .B (state[0]), .Y (n_45));
  NOR2X4 g5503__5115(.A (LED[2]), .B (\LED[1]_402 ), .Y (n_16));
  NOR2X4 g5501__7482(.A (\LED[7]_408 ), .B (\LED[6]_407 ), .Y (n_15));
  NAND2X6 g5500__4733(.A (LED[2]), .B (\LED[0]_401 ), .Y (n_14));
  NOR2X6 g5502__6161(.A (\LED[10]_411 ), .B (LED[11]), .Y (n_12));
  NOR2X8 g5508__9315(.A (\LED[13]_414 ), .B (LED[12]), .Y (n_11));
  NOR2X6 g5510__9945(.A (\LED[14]_415 ), .B (LED[5]), .Y (n_10));
  CLKAND2X2 g5507__2883(.A (LED[3]), .B (LED[4]), .Y (n_9));
  NOR2X6 g5505__2346(.A (min_max_key[0]), .B (min_max_key[1]), .Y
       (n_69));
  CLKINVX4 g5532(.A (LED[8]), .Y (n_7));
  INVX2 g5516(.A (min_max_key[0]), .Y (n_6));
  INVX6 g5531(.A (state[1]), .Y (n_13));
  CLKINVX8 g5538(.A (LED[11]), .Y (n_25));
  INVX1 g5522(.A (state[0]), .Y (n_49));
  INVXL g5521(.A (RST), .Y (n_91));
  AOI21X4 g5561__1666(.A0 (LED[1]), .A1 (n_119), .B0 (n_165), .Y
       (n_129));
  OAI2BB1X4 g5563__7410(.A0N (state[0]), .A1N (n_101), .B0 (n_85), .Y
       (n_123));
  NAND2X8 g5565__6417(.A (n_63), .B (n_55), .Y (n_68));
  CLKINVX8 fopt5572(.A (\LED[1]_402 ), .Y (n_158));
  CLKINVX16 fopt5575(.A (n_165), .Y (n_168));
  CLKINVX20 fopt5577(.A (n_136), .Y (n_165));
  CLKINVX4 fopt5578(.A (\LED[0]_401 ), .Y (n_176));
  CLKINVX4 fopt5584(.A (\LED[7]_408 ), .Y (n_183));
  CLKINVX8 fopt5588(.A (\LED[14]_415 ), .Y (n_185));
  CLKINVX4 fopt5593(.A (LED[3]), .Y (n_190));
  CLKINVX8 fopt5605(.A (n_212), .Y (LED[6]));
  CLKINVX8 fopt5606(.A (\LED[6]_407 ), .Y (n_212));
  CLKBUFX6 fopt5609(.A (n_69), .Y (n_214));
  CLKINVX8 fopt5615(.A (min_max_key[1]), .Y (n_219));
  INVX6 fopt5624(.A (LED[4]), .Y (n_230));
  CLKINVX4 fopt5628(.A (\LED[13]_414 ), .Y (n_241));
  CLKINVX4 fopt5631(.A (\LED[10]_411 ), .Y (n_245));
  NAND2X6 g5641__2398(.A (n_77), .B (n_78), .Y (n_79));
  INVX3 g5643(.A (n_81), .Y (n_82));
  NAND2X4 g5649__5107(.A (LED[2]), .B (n_43), .Y (n_44));
  NAND2X6 g5657__6260(.A (n_15), .B (n_10), .Y (n_38));
  NAND2X6 g5675__4319(.A (n_16), .B (n_19), .Y (n_66));
  NAND2X6 g5677__8428(.A (n_66), .B (n_65), .Y (n_67));
  BUFX16 fopt5701(.A (n_118), .Y (n_274));
  OAI2BB2X4 g2(.A0N (LED[15]), .A1N (n_274), .B0 (n_185), .B1 (n_168),
       .Y (n_280));
  AO22X1 g5702(.A0 (n_41), .A1 (n_89), .B0 (state[0]), .B1 (n_100), .Y
       (n_281));
  BUFX2 fopt5704(.A (\LED[0]_401 ), .Y (LED[0]));
  BUFX2 fopt5706(.A (min_max_key[1]), .Y (n_220));
  INVX1 fopt5708(.A (LED[12]), .Y (n_199));
  INVX1 fopt5710(.A (LED[2]), .Y (n_201));
  INVX1 fopt5712(.A (n_185), .Y (LED[14]));
  INVX2 fopt5714(.A (n_241), .Y (LED[13]));
  INVX2 fopt5716(.A (n_245), .Y (LED[10]));
  INVX2 fopt5718(.A (n_183), .Y (LED[7]));
  INVX1 fopt5720(.A (n_158), .Y (LED[1]));
  INVX2 g5722(.A (n_100), .Y (n_101));
  INVX2 fopt5724(.A (n_220), .Y (n_222));
  INVX3 fopt5726(.A (n_214), .Y (n_215));
endmodule

